WITH MONTHLY_REVENUE AS (
        SELECT 
        D.YEAR, D.MONTH, D.MONTH_NAME, SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
        FROM FACT_ORDER_LINE F
        JOIN DIM_DATE D ON F.DATE_KEY = D.DATE_KEY
        GROUP BY D.YEAR, D.MONTH, D.MONTH_NAME
),
YOY_COMPARISON AS (
    SELECT 
        YEAR, MONTH, MONTH_NAME, TOTAL_REVENUE AS CURRENT_YEAR_REVENUE,
        LAG(TOTAL_REVENUE) OVER (PARTITION BY MONTH ORDER BY YEAR) AS PREVIOUS_YEAR_REVENUE
    FROM MONTHLY_REVENUE
)
SELECT 
    YEAR, MONTH, MONTH_NAME, CURRENT_YEAR_REVENUE, PREVIOUS_YEAR_REVENUE,
    CURRENT_YEAR_REVENUE - PREVIOUS_YEAR_REVENUE AS YOY_CHANGE,
    ROUND(((CURRENT_YEAR_REVENUE - PREVIOUS_YEAR_REVENUE) / NULLIF(PREVIOUS_YEAR_REVENUE, 0)) * 100, 2) AS YOY_PERCENT_CHANGE
    FROM YOY_COMPARISON
WHERE PREVIOUS_YEAR_REVENUE IS NOT NULL 
ORDER BY MONTH, YEAR;