-- Active: 1773756114201@@127.0.0.1@3306@ecommerce_dw
WITH MONTHLY_METRICS AS (
    SELECT
    D.YEAR, D.MONTH, D.MONTH_NAME,
    SUM(F.NET_AMOUNT) AS CURRENT_MONTHLY_REVENUE
    FROM FACT_ORDER_LINE F
    JOIN DIM_DATE D ON F.DATE_KEY = D.DATE_KEY
    GROUP BY D.YEAR, D.MONTH, D.MONTH_NAME
),
MOM_COMPARISON AS (
    SELECT 
        YEAR, MONTH, MONTH_NAME, CURRENT_MONTHLY_REVENUE,
        LAG(CURRENT_MONTHLY_REVENUE) OVER (ORDER BY YEAR, MONTH) AS PREVIOUS_MONTHLY_REVENUE
    FROM MONTHLY_METRICS
)
SELECT 
    YEAR, MONTH, MONTH_NAME, CURRENT_MONTHLY_REVENUE, PREVIOUS_MONTHLY_REVENUE,
    CURRENT_MONTHLY_REVENUE - PREVIOUS_MONTHLY_REVENUE AS MOM_CHANGE,
    CASE 
        WHEN PREVIOUS_MONTHLY_REVENUE IS NULL THEN NULL
        ELSE ROUND(((CURRENT_MONTHLY_REVENUE - PREVIOUS_MONTHLY_REVENUE) / NULLIF(PREVIOUS_MONTHLY_REVENUE, 0)) * 100, 2)
    END AS MOM_PERCENT_CHANGE
    FROM MOM_COMPARISON
ORDER BY YEAR, MONTH;