WITH ORDER_TOTALS AS (
    SELECT 
    C.CUSTOMER_ID, D.FULL_DATE, F.ORDER_ID, SUM(F.NET_AMOUNT) AS ORDER_AMOUNT
    FROM FACT_ORDER_LINE F
    JOIN DIM_DATE D ON F.DATE_KEY = D.DATE_KEY
    JOIN DIM_CUSTOMER C ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
    GROUP BY C.CUSTOMER_ID, D.FULL_DATE, F.ORDER_ID
)
SELECT 
    CUSTOMER_ID, FULL_DATE,ORDER_ID, ORDER_AMOUNT,
    SUM(ORDER_AMOUNT) OVER (PARTITION BY CUSTOMER_ID ORDER BY FULL_DATE, ORDER_ID) AS CUMULATIVE_SPEND
    FROM ORDER_TOTALS
    ORDER BY CUSTOMER_ID, FULL_DATE, ORDER_ID;