WITH CUSTOMER_ORDERS AS (
    SELECT DISTINCT
        C.CUSTOMER_ID, F.ORDER_ID, D.FULL_DATE AS CURRENT_ORDER_DATE
        FROM fact_order_line F 
        JOIN dim_customer C ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
        JOIN dim_date D ON F.DATE_KEY = D.DATE_KEY
),
ORDER_SEQUENCE AS (
    SELECT 
        customer_id, order_id, CURRENT_ORDER_DATE,
        LAG(CURRENT_ORDER_DATE) OVER (PARTITION BY customer_id ORDER BY CURRENT_ORDER_DATE, ORDER_ID) AS PREVIOUS_ORDER_DATE
    FROM CUSTOMER_ORDERS
)
SELECT 
    customer_id, order_id, CURRENT_ORDER_DATE, PREVIOUS_ORDER_DATE,
    DATEDIFF(CURRENT_ORDER_DATE, PREVIOUS_ORDER_DATE) AS DAYS_BETWEEN_ORDERS
    FROM ORDER_SEQUENCE
    ORDER BY customer_id, CURRENT_ORDER_DATE 