WITH BRAND_CATEGORY_PROFIT AS (
    SELECT
        C.CATEGORY_NAME,
        P.BRAND,
        SUM(F.PROFIT_AMOUNT) AS TOTAL_PROFIT
    FROM FACT_ORDER_LINE F
    JOIN DIM_PRODUCT P ON F.PRODUCT_KEY = P.PRODUCT_KEY
    JOIN DIM_CATEGORY C ON F.CATEGORY_KEY = C.CATEGORY_KEY
    GROUP BY C.CATEGORY_NAME, P.BRAND

)
SELECT
    CATEGORY_NAME,
    BRAND,
    TOTAL_PROFIT,
    DENSE_RANK() OVER (PARTITION BY CATEGORY_NAME ORDER BY TOTAL_PROFIT DESC) AS BRAND_RANK
    FROM BRAND_CATEGORY_PROFIT
ORDER BY CATEGORY_NAME, BRAND_RANK;